### ISSUE TITLE
無法正常撈取留言

### ISSUE THREAD

**Issue by GhMoose** [dghkd/KomeTubeR#1]
您好
近期有撈聊天室訊息的需求, 找到了您的程式
不過目前無法正常使用
看起來似乎是爬html的部分出問題
不知道方不方便麻煩您確認一下呢
謝謝

**Comment by dghkd** [comment]
已嘗試修正  
請使用2.0.0.12310版  
https://github.com/dghkd/KomeTubeR/releases/tag/2.0.0.12310

commit: e58f50139e7c444016db4e596da65e88d033ce32
